name: Build Padavan

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  # schedule:
  #   - cron: 0 8 * * 5
  workflow_dispatch:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano \
        xxd fakeroot kmod cpio git python-docutils python3-docutils gettext automake \
        autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
        
    - name: Clone source code
      env:
        KERNEL: 4.4
      run: |
        if [ $KERNEL = "4.4" ] ; then
        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
        else
        git clone --depth=1 https://github.com/chongshengB/rt-n56u.git /opt/rt-n56u
        fi
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/

    - name: Adjust Config
      env:
        TNAME: RM2100
        KERNEL: 4.4
      run: |
        #########################################################################################
        #更新Adguardhome二进制文件
        cd /opt/rt-n56u/trunk/user/adguardhome
        rm AdGuardHome
        wget https://github.com/AdguardTeam/AdGuardHome/releases/download/\
        $(curl -Ls "https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')\
        /AdGuardHome_linux_mipsle_softfloat.tar.gz -qO agh.tar.gz
        tar -xf agh.tar.gz -C ./ --strip-components=2 ./AdGuardHome/AdGuardHome
        #修改adguardhome.sh脚本
        sed -i '/\"\/tmp\/AdGuardHome\/AdGuardHome\"/{N;N;d;}' adguardhome.sh
        sed -i 's/\/tmp\/AdGuardHome\/AdGuardHome/\/usr\/bin\/Adguardhome/g' adguardhome.sh
        #########################################################################################
        #配置路由器基础信息
        cd /opt/rt-n56u/trunk/user/shared
        sed -i 's/"192.168.2.1"/"192.168.1.254"/g' defaults.h #修改本机LAN口IP
        sed -i 's/"192.168.2.100"/"192.168.1.50"/g' defaults.h #修改DHCP起始IP
        sed -i 's/"192.168.2.244"/"192.168.1.230"/g' defaults.h #修改DHCP末位IP
        sed -i 's/"CN"/"AU"/g' defaults.h #修改无线网络代码
        sed -i 's/"1234567890"/"88888888"/g' defaults.h #修改默认WIFI密码
        #########################################################################################
        # 检查是否有该机型模板文件
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        ################################################################################################
        #配置软件
        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条。
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config #删除配置项MENTOHUST
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config #删除配置项WIREGUARD
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config #删除配置项FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config #删除配置项FRPC
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config #删除配置项TUNSAFE
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config #删除配置项SCUTCLIENT
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config #删除配置项SS plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config #删除配置项SS server
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config #删除配置项DNSFORWARDER
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ADBYBY/d' .config #删除配置项adbyby plus+
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config #删除配置项阿里DDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config #删除配置项SMARTDNS
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config 
        ######################################################################
        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
        echo "CONFIG_FIRMWARE_INCLUDE_ADGUARDHOME=y" >> .config #adguardhome
        echo "CONFIG_FIRMWARE_INCLUDE_OC=y" >> .config #CPU超频开关
        echo "CONFIG_FIRMWARE_MT7621_OC="0x362"" >> .config #此处填写对应频率的十六进制：1000Mhz=0x312 1100Mhz=0x362 1120Mhz=0x372 1200Mhz=0x3B2
        
    - name: Build Firmware
      env:
        TNAME: RM2100
      run: |
        cd /opt/rt-n56u/trunk
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
        
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: Padavan-packages
        path: /opt/images
